<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="PC-NamLe" failures="1" tests="9" name="Run All Tests" time="30.919" errors="0" timestamp="2025-06-24T10:05:25 ICT">
  <testcase classname="com.nam.qa.practice.CheckOutTest" name="verifyCancelButtonNavigatesBackToCartPage" time="1.157"/>
  <testcase classname="com.nam.qa.practice.CheckOutTest" name="verifyErrorMessageWhenFirstNameIsEmpty" time="1.253"/>
  <testcase classname="com.nam.qa.practice.CheckOutTest" name="verifyErrorMessageWhenLastNameIsEmpty" time="1.251"/>
  <testcase classname="com.nam.qa.practice.CheckOutTest" name="verifyErrorMessageWhenPostalCodeIsEmpty" time="1.23"/>
  <testcase classname="com.nam.qa.practice.CheckOutTest" name="verifyCannotCheckoutWithEmptyCart" time="1.007">
    <failure type="java.lang.AssertionError" message="❌ Checkout proceeded even with empty cart! expected [https://www.saucedemo.com/checkout-step-one.html] but found [https://www.saucedemo.com/checkout-step-two.html]">
      <![CDATA[java.lang.AssertionError: ❌ Checkout proceeded even with empty cart! expected [https://www.saucedemo.com/checkout-step-one.html] but found [https://www.saucedemo.com/checkout-step-two.html]
at com.nam.qa.practice.CheckOutTest.verifyCannotCheckoutWithEmptyCart(CheckOutTest.java:101)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
... Removed 30 stack frames]]>
    </failure>
  </testcase> <!-- verifyCannotCheckoutWithEmptyCart -->
  <testcase classname="com.nam.qa.practice.CheckOutTest" name="verifyTotalAmountWithSingleProduct" time="1.297"/>
  <testcase classname="com.nam.qa.practice.CheckOutTest" name="verifyTotalAmountWithMutipleProduct" time="4.273"/>
  <testcase classname="com.nam.qa.practice.CheckOutTest" name="verifyMessageWhenCheckOutSuccessfully" time="1.448"/>
  <testcase classname="com.nam.qa.practice.CheckOutTest" name="verifyButtonBackHomeNavigatesBackToProductPage" time="1.705"/>
</testsuite> <!-- Run All Tests -->
