<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="PC-NamLe" failures="1" tests="9" name="com.nam.qa.practice.CheckOutTest" time="22.952" errors="0" timestamp="2025-06-24T09:57:05 ICT" skipped="0">
  <testcase classname="com.nam.qa.practice.CheckOutTest" name="verifyCancelButtonNavigatesBackToCartPage" time="1.650"/>
  <testcase classname="com.nam.qa.practice.CheckOutTest" name="verifyErrorMessageWhenFirstNameIsEmpty" time="1.856"/>
  <testcase classname="com.nam.qa.practice.CheckOutTest" name="verifyErrorMessageWhenLastNameIsEmpty" time="1.973"/>
  <testcase classname="com.nam.qa.practice.CheckOutTest" name="verifyErrorMessageWhenPostalCodeIsEmpty" time="1.898"/>
  <testcase classname="com.nam.qa.practice.CheckOutTest" name="verifyCannotCheckoutWithEmptyCart" time="1.584">
    <failure message="❌ Checkout proceeded even with empty cart! expected [https://www.saucedemo.com/checkout-step-one.html] but found [https://www.saucedemo.com/checkout-step-two.html]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: ❌ Checkout proceeded even with empty cart! expected [https://www.saucedemo.com/checkout-step-one.html] but found [https://www.saucedemo.com/checkout-step-two.html]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1590)
at org.testng.Assert.assertEqualsImpl(Assert.java:150)
at org.testng.Assert.assertEquals(Assert.java:132)
at org.testng.Assert.assertEquals(Assert.java:656)
at com.nam.qa.practice.CheckOutTest.verifyCannotCheckoutWithEmptyCart(CheckOutTest.java:101)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:687)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:230)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:995)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:741)
at org.testng.TestRunner.run(TestRunner.java:616)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:413)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:373)
at org.testng.SuiteRunner.run(SuiteRunner.java:312)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1274)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1208)
at org.testng.TestNG.runSuites(TestNG.java:1112)
at org.testng.TestNG.run(TestNG.java:1079)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
    </failure>
  </testcase> <!-- verifyCannotCheckoutWithEmptyCart -->
  <testcase classname="com.nam.qa.practice.CheckOutTest" name="verifyTotalAmountWithSingleProduct" time="2.151"/>
  <testcase classname="com.nam.qa.practice.CheckOutTest" name="verifyTotalAmountWithMutipleProduct" time="5.185"/>
  <testcase classname="com.nam.qa.practice.CheckOutTest" name="verifyMessageWhenCheckOutSuccessfully" time="2.245"/>
  <testcase classname="com.nam.qa.practice.CheckOutTest" name="verifyButtonBackHomeNavigatesBackToProductPage" time="4.410"/>
</testsuite> <!-- com.nam.qa.practice.CheckOutTest -->
