<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="PC-NamLe" failures="2" tests="14" name="com.nam.qa.practice.ProductTest" time="18.564" errors="0" timestamp="2025-06-23T16:08:15 ICT" skipped="0">
  <testcase classname="com.nam.qa.practice.ProductTest" name="verifyCartIcon" time="0.541"/>
  <testcase classname="com.nam.qa.practice.ProductTest" name="ProductListisDisplayed" time="0.540"/>
  <testcase classname="com.nam.qa.practice.ProductTest" name="verifyProductNameMatchBetweenDetailPage" time="1.613"/>
  <testcase classname="com.nam.qa.practice.ProductTest" name="verifyProductDescriptionMatchBetweenDetailPage" time="1.746"/>
  <testcase classname="com.nam.qa.practice.ProductTest" name="verifyProductPriceMatchBetweenDetailPage" time="2.500"/>
  <testcase classname="com.nam.qa.practice.ProductTest" name="verifyProductImageMatchBetweenDetailPage" time="1.471"/>
  <testcase classname="com.nam.qa.practice.ProductTest" name="verifyAddtoCartFromProductPage" time="0.874"/>
  <testcase classname="com.nam.qa.practice.ProductTest" name="verifyAddtoCartFromDetailPage" time="2.115"/>
  <testcase classname="com.nam.qa.practice.ProductTest" name="verifyRemoveFromProductPage" time="1.627"/>
  <testcase classname="com.nam.qa.practice.ProductTest" name="verifyRemoveProductFromDetailPage" time="2.120"/>
  <testcase classname="com.nam.qa.practice.ProductTest" name="verifyNavigationFromTileToDetailPage" time="0.438">
    <failure message="❌ Fail Page. Expected URL have contains &#039;inventory-item.html&#039; expected [true] but found [false]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: ❌ Fail Page. Expected URL have contains 'inventory-item.html' expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1590)
at org.testng.Assert.assertTrue(Assert.java:57)
at com.nam.qa.practice.ProductTest.verifyNavigationFromTileToDetailPage(ProductTest.java:258)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:687)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:230)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:995)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:741)
at org.testng.TestRunner.run(TestRunner.java:616)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:413)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:373)
at org.testng.SuiteRunner.run(SuiteRunner.java:312)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1274)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1208)
at org.testng.TestNG.runSuites(TestNG.java:1112)
at org.testng.TestNG.run(TestNG.java:1079)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
    </failure>
  </testcase> <!-- verifyNavigationFromTileToDetailPage -->
  <testcase classname="com.nam.qa.practice.ProductTest" name="verifyNavigationImgFromToDetailPage" time="0.416">
    <failure message="❌ Fail Page. tadaa Expected URL have contains &#039;inventory-item.html&#039; expected [true] but found [false]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: ❌ Fail Page. tadaa Expected URL have contains 'inventory-item.html' expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1590)
at org.testng.Assert.assertTrue(Assert.java:57)
at com.nam.qa.practice.ProductTest.verifyNavigationImgFromToDetailPage(ProductTest.java:271)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:687)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:230)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:995)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:741)
at org.testng.TestRunner.run(TestRunner.java:616)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:413)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:373)
at org.testng.SuiteRunner.run(SuiteRunner.java:312)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1274)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1208)
at org.testng.TestNG.runSuites(TestNG.java:1112)
at org.testng.TestNG.run(TestNG.java:1079)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
    </failure>
  </testcase> <!-- verifyNavigationImgFromToDetailPage -->
  <testcase classname="com.nam.qa.practice.ProductTest" name="verifyButtonBackToProductFromDetailPage" time="1.455"/>
  <testcase classname="com.nam.qa.practice.ProductTest" name="verifyMenuProduct" time="1.108"/>
</testsuite> <!-- com.nam.qa.practice.ProductTest -->
